"use client";
import Head from "next/head";
import "./globals.css";
import { Montserrat } from "next/font/google";
import Navbar from "./components/navbar";
import Footer from "./components/footer";

const montserrat = Montserrat({
    subsets: ["latin"],
    variable: "--font-mont",
});

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <Head>
                <title>Portfolio</title>
                <meta content="width=device-width, initial-scale=1" name="viewport" />
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <body>
                <Navbar />
                <main className={`${montserrat.variable} font-mont bg-light w-full min-h-screen`}>{children}</main>
                <Footer />
            </body>
        </html>
    );
}
